export const COUNTRIES = [
  { label: 'United States', value: 'USA' },
  { label: 'Canada', value: 'Canada' },
  { label: 'United Kingdom', value: 'UK' },
  { label: 'Sweden', value: 'Sweden' },
  { label: 'Egypt', value: 'Egypt' },
  { label: 'Saudi Arabia', value: 'Saudi Arabia' },
  { label: 'United Arab Emirates', value: 'UAE' },
  { label: 'Jordan', value: 'Jordan' },
  { label: 'Lebanon', value: 'Lebanon' },
  { label: 'Kuwait', value: 'Kuwait' },
  { label: 'Oman', value: 'Oman' },
  { label: 'Qatar', value: 'Qatar' },
  { label: 'Bahrain', value: 'Bahrain' },
  { label: 'Iraq', value: 'Iraq' },
  { label: 'Syria', value: 'Syria' },
  { label: 'Yemen', value: 'Yemen' },
  { label: 'Palestine', value: 'Palestine' },
  { label: 'Libya', value: 'Libya' },
  { label: 'Sudan', value: 'Sudan' },
  { label: 'Morocco', value: 'Morocco' },
  { label: 'Tunisia', value: 'Tunisia' },
  { label: 'Algeria', value: 'Algeria' },
  { label: 'Mauritania', value: 'Mauritania' },
  { label: 'Somalia', value: 'Somalia' },
  { label: 'Djibouti', value: 'Djibouti' },
  { label: 'Comoros', value: 'Comoros' },
  { label: 'France', value: 'France' },
  { label: 'Germany', value: 'Germany' },
  { label: 'Italy', value: 'Italy' },
  { label: 'Spain', value: 'Spain' },
  { label: 'Turkey', value: 'Turkey' },
  { label: 'Netherlands', value: 'Netherlands' },
  { label: 'Switzerland', value: 'Switzerland' },
  { label: 'Belgium', value: 'Belgium' },
  { label: 'Austria', value: 'Austria' },
  { label: 'Portugal', value: 'Portugal' },
  { label: 'Greece', value: 'Greece' },
  { label: 'Denmark', value: 'Denmark' },
  { label: 'Finland', value: 'Finland' },
  { label: 'Norway', value: 'Norway' },
  { label: 'Ireland', value: 'Ireland' },
  { label: 'Australia', value: 'Australia' },
  { label: 'New Zealand', value: 'New Zealand' },
  { label: 'China', value: 'China' },
  { label: 'Japan', value: 'Japan' },
  { label: 'India', value: 'India' },
  { label: 'Brazil', value: 'Brazil' },
  { label: 'Mexico', value: 'Mexico' }
];
